language: node_js

addons:
  sonarcloud:
    organization: "woobens-github"
script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_NODE_VERSION" = '14' && "$TRAVIS_BRANCH" = "master" ]]; then
      npm run test:cov && sonar-scanner;
    fi
  - npm run test

cache:
  directories:
    - node_modules

os:
  - osx
  # - windows
  - linux

node_js:
  - 10
  - 11
  - 12
  - 13
  - 14
